import os
from dotenv import load_dotenv

load_dotenv()

# Supabase
SUPABASE_URL = "https://knoluipowadknsjabcqo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtub2x1aXBvd2Fka25zamFiY3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjYxMDA0MTksImV4cCI6MjA0MTY3NjQxOX0.LDgUKgjnglG5nNQ_IH4mzmEM89McJafbFrbvhoSETSQ"
